name: DisneyHotstar

on:
  push:
    branches: [ main ]
 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: yeboahd24/heroku_deploy@v3.4.6
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        heroko_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: 'disneyhotstar'
        heroku_email: 'yeboahd24@gmail.com'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Successful Message
      run: |
        echo Successfully Deployed!
